bms/config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :apartments
  root 'apartments#index'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'

  match '/about', to: 'static_pages#about', via: 'get'

  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

  match '/posts', to: 'static_pages#home', via: 'get'

end

bms/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

bms/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

bms/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body>
<noscript>
  <p>Enable JavaScript</p>
</noscript>

<div class="frame_outer">
  <a name="top" id="top"></a>

  <script>
      //function to fix height of iframe!
      var calcHeight = function () {
          var headerDimensions = $('.preview__header').height();
          $('.full-screen-preview__frame').height($(window).height() - headerDimensions);
      }

      $(document).ready(function () {
          calcHeight();
      });

      $(window).resize(function () {
          calcHeight();
      }).load(function () {
          calcHeight();
      });
  </script>
  <!--▼HEADER-->
  <div id="header_wrap" style="min-height: 56px;">
    <div id="header" class="clearfix full-screen-preview" style="width: 100%;">
      <div id="top-strip">
        <div class="container" style="padding-left: 3px; padding-right: 0px;">
          <ul class="pull-left social-icons" style="margin-bottom: 0;">
            <li><a href="#" class="fa fa-google-plus"></a></li>
            <li><a href="#" class="fa fa-twitter"></a></li>
            <li><a href="#" class="fa fa-pinterest"></a></li>
            <li><a href="#" class="fa fa-dribbble"></a></li>
            <li><a href="#" class="fa fa-linkedin"></a></li>
            <li><a href="#" class="fa fa-facebook"></a></li>
          </ul>
          <div id="login-box" class="pull-right">
            <% if signed_in? %>
                <%= link_to "<span>Users</span>".html_safe, users_path, :class => "fa fa-user", :style => "color: #fff" %>
                <%= link_to "<span>Profile</span>".html_safe, current_user, :class => "fa fa-pencil", :style => "padding-left: 20px" %>
                <%= link_to "<span>Sign out</span>".html_safe, signout_path, method: "delete", :style => "padding-left: 20px" %>
            <% else %>
                <%= link_to "<span>Login</span>".html_safe, signin_path, :class => "fa fa-user", :style => "color: #fff" %>
                <%= link_to "<span>Register</span>".html_safe, signup_path, :class => "fa fa-pencil", :style => "padding-left: 20px; color: #fff" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="premium-bar">
    <div class="container">
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid" style="padding: 0;">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to apartments_path, class:"navbar-brand", style:"padding-left:0" do %>
                <%= image_tag "logo_dreamhome.png", :width => 250 %>
            <% end %>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="padding: 0;">
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Feed", posts_path %></li>
              <li><%= link_to "About Us", about_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
              <li><%= link_to "Help", help_path %></li>
            </ul>
          </div>
          <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
      </nav>
    </div>
  </div>
  <!--▲HEADER-->

  <%= yield %>
  <!--▼FOOTER-->
  <script>
      function backToTop() {
          $("html, body").animate({scrollTop: 0}, 700);
      }
  </script>
  <div style="clear: both;"></div>
  <div id="footer_wrap">
    <div id="footer" class="clearfix">
      <div id="copyright">
        Copyright &copy; Dream Home 2014&nbsp;&nbsp;|&nbsp;&nbsp;Designed by TDA
      </div>
      <div id="pagetop">
        <a onclick="backToTop();">
          <%= image_tag "backtotop.png" ,:class => 'backtop'%>
        </a>
      </div>
      <ul class="pull-right social-icons" style="margin-bottom: 0; padding-top: 15px;">
        <li><a href="#" class="fa fa-google-plus"></a></li>
        <li><a href="#" class="fa fa-twitter"></a></li>
        <li><a href="#" class="fa fa-pinterest"></a></li>
        <li><a href="#" class="fa fa-dribbble"></a></li>
        <li><a href="#" class="fa fa-linkedin"></a></li>
        <li><a href="#" class="fa fa-facebook"></a></li>
      </ul>
    </div>
  </div>
  <!--▲FOOTER-->
</body>
</html>