bms/config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :apartments
  root 'apartments#index'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'

  match '/about', to: 'static_pages#about', via: 'get'

  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

  match '/posts', to: 'static_pages#home', via: 'get'

end

bms/app/models/apartment.rb
class Apartment < ActiveRecord::Base
  validates :room, presence: true, length: {maximum: 50}
  validates :floor, presence: true
  validates :area, presence: true
  validates :price, presence: true

end

bms/app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
	def index
		@apartments = Apartment.all
	end
	def new
		@apartment = Apartment.new
	end
	def create
		@apartment=Apartment.new(apartment_params)
		if(@apartment.save)
			redirect_to @apartment
		else
			render 'new'
		end
	end
	def show
		@apartment = Apartment.find(params[:id])
	end	
	def edit
		@apartment = Apartment.find(params[:id])
	end
	def update
		@apartment = Apartment.find(params[:id])

		if @apartment.update(apartment_params)
			redirect_to @apartment
		else
			render 'edit'
		end
	end
	def destroy
		@apartment = Apartment.find(params[:id])
		@apartment.destroy
		redirect_to apartments_path
	end
	private
	def apartment_params
		params.require(:apartment).permit(:room, :floor, :area, :price)
	end
end

bms/app/helpers/apartments_helper.rb
module ApartmentsHelper
end

bms/app/views/apartments/_form.html.erb
<%= form_for @apartment do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <p>
    <%= f.label :room %>
    <%= f.text_field :room %>
  </p>
 
  <p>
    <%= f.label :floor %>
    <%= f.text_field :floor %>
  </p>

  <p>
    <%= f.label :area %>
    <%= f.text_field :area %>
  </p>
  <p>
    <%= f.label :price %> 
    <%= f.text_field :price %>
  </p>
 
  <p class="submit">
    <%= f.submit %>
  </p>
<% end %>

bms/app/views/apartments/edit.html.erb
<div class="block-border">
	<div class="block-content">
		<h2>Edit apartment</h2>
		<%= render 'form' %>
	</div>
</div>

bms/app/views/apartments/index.html.erb
<!-- ▼block_panel -->
<script>
jQuery(document).ready(function($) {

    var _SlideshowTransitions = [
                //Fade in R
                {$Duration: 1200, x: -0.3, $During: { $Left: [0.3, 0.7] }, $Easing: { $Left: $JssorEasing$.$EaseInCubic, $Opacity: $JssorEasing$.$EaseLinear }, $Opacity: 2 }
        //Fade out L
        , { $Duration: 1200, x: 0.3, $SlideOut: true, $Easing: { $Left: $JssorEasing$.$EaseInCubic, $Opacity: $JssorEasing$.$EaseLinear }, $Opacity: 2 }
        ];
        var options = {
                    $AutoPlay: true, //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
                    $AutoPlaySteps: 1, //[Optional] Steps to go for each navigation request (this options applys only when slideshow disabled), the default value is 1
                    $AutoPlayInterval: 4000, //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
                    $PauseOnHover: 1, //[Optional] Whether to pause when mouse over if a slider is auto playing, 0 no pause, 1 pause for desktop, 2 pause for touch device, 3 pause for desktop and touch device, 4 freeze for desktop, 8 freeze for touch device, 12 freeze for desktop and touch device, default value is 1

                    $ArrowKeyNavigation: true, //[Optional] Allows keyboard (arrow key) navigation or not, default value is false
                    $SlideDuration: 500, //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
                    $MinDragOffsetToSlide: 20, //[Optional] Minimum drag offset to trigger slide , default value is 20
                    //$SlideWidth: 600,                                 //[Optional] Width of every slide in pixels, default value is width of 'slides' container
                    //$SlideHeight: 300,                                //[Optional] Height of every slide in pixels, default value is height of 'slides' container
                    $SlideSpacing: 0, //[Optional] Space between each slide in pixels, default value is 0
                    $DisplayPieces: 1, //[Optional] Number of pieces to display (the slideshow would be disabled if the value is set to greater than 1), the default value is 1
                    $ParkingPosition: 0, //[Optional] The offset position to park slide (this options applys only when slideshow disabled), default value is 0.
                    $UISearchMode: 1, //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).
                    $PlayOrientation: 1, //[Optional] Orientation to play slide (for auto play, navigation), 1 horizental, 2 vertical, 5 horizental reverse, 6 vertical reverse, default value is 1
                    $DragOrientation: 3, //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)

                    $SlideshowOptions: {//[Optional] Options to specify and enable slideshow or not
                        $Class: $JssorSlideshowRunner$, //[Required] Class to create instance of slideshow
                        $Transitions: _SlideshowTransitions, //[Required] An array of slideshow transitions to play slideshow
                        $TransitionsOrder: 1, //[Optional] The way to choose transition to play slide, 1 Sequence, 0 Random
                        $ShowLink: true                                    //[Optional] Whether to bring slide link on top of the slider when slideshow is running, default value is false
                    },
                    $BulletNavigatorOptions: {//[Optional] Options to specify and enable navigator or not
                        $Class: $JssorBulletNavigator$, //[Required] Class to create navigator instance
                        $ChanceToShow: 2, //[Required] 0 Never, 1 Mouse Over, 2 Always
                        $Lanes: 1, //[Optional] Specify lanes to arrange items, default value is 1
                        $SpacingX: 10, //[Optional] Horizontal space between each item in pixel, default value is 0
                        $SpacingY: 10                                    //[Optional] Vertical space between each item in pixel, default value is 0
                    },
                    $ArrowNavigatorOptions: {
                        $Class: $JssorArrowNavigator$, //[Requried] Class to create arrow navigator instance
                        $ChanceToShow: 2, //[Required] 0 Never, 1 Mouse Over, 2 Always
                        $AutoCenter: 2                                 //[Optional] Auto center navigator in parent container, 0 None, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
                    },
                    $ThumbnailNavigatorOptions: {
                        $Class: $JssorThumbnailNavigator$, //[Required] Class to create thumbnail navigator instance
                        $ChanceToShow: 2, //[Required] 0 Never, 1 Mouse Over, 2 Always
                        $ActionMode: 0, //[Optional] 0 None, 1 act by click, 2 act by mouse hover, 3 both, default value is 1
                        $DisableDrag: true                              //[Optional] Disable drag or not, default value is false
                    }
                };

                var jssor_sliderb = new $JssorSlider$("sliderb_container", options);
        //responsive code begin
        //you can remove responsive code if you don't want the slider scales while window resizes
        function ScaleSlider() {
            var parentWidth = jssor_sliderb.$Elmt.parentNode.clientWidth;
            var mywidth = '100%';
            if (parentWidth)
                jssor_sliderb.$ScaleWidth(Math.min(parentWidth, mywidth));
            else
                window.setTimeout(ScaleSlider, 30);
        }

        ScaleSlider();

        if (!navigator.userAgent.match(/(iPhone|iPod|iPad|BlackBerry|IEMobile)/)) {
            $(window).bind('resize', ScaleSlider);
        }

    });
</script>
<div id="sliderb_container" class="slide_container">

    <!-- Loading Screen -->
    <div u="loading" style="position: absolute; top: 0px; left: 0px;">
        <div class="loading_banner">
        </div>
        <div class="loading_under">
        </div>
    </div>

    <!-- Slides Container -->
    <div u="slides" class="slide_content">
        <div>
            <%= image_tag "slide-01.jpg"%>
        </div>
        <div>
            <%= image_tag "slide-02.jpg"%>
        </div>
        <div>
            <%= image_tag "slide-03.jpg"%>
        </div>
        <div>
            <%= image_tag "slide-04.jpg"%>
        </div>
        <div>
            <%= image_tag "slide-05.jpg"%>
        </div>
    </div>

    <span u="arrowleft" class="jssora05l" style="width: 61px; height: 61px; top: 123px; left: 0px;">
        <%= image_tag "Left_Slide.png", :width => 61, :height =>61 %>
    </span>
    <!-- Arrow Right -->
    <span u="arrowright" class="jssora05r" style="width: 61px; height: 61px; top: 123px; right: 0px">
        <%= image_tag "Right_Slide.png", :width => 61, :height =>61 %>
    </span>
    <!-- Arrow Navigator Skin End -->
    <div class="hotline">
        <%= image_tag "HotLine_Slide.png" %>
    </div>
</div>                                        
<!-- ▲block_panel -->
<!-- ▼block_listings -->
<div style="clear: both;"></div>
<div class="recent-listings" style="background: #EBEBEC;">
    <div class="container">
        <div class="title-box">
            <h3>Apartment <%= link_to "", new_apartment_path, class:"fa fa-plus" %></h3>
            <div class="bordered">
            </div>
        </div>
        <div class="row listings-items-wrapper">
            <% @apartments.each do |apartment| %>
            <!-- Single-item -->
            <div class="col-md-4 listing-single-item">
                <div class="item-inner">
                    <div class="image-wrapper">
                        <%= link_to apartment_path(apartment) do %>
                        <%= image_tag "07_img-6.png" ,:class => 'backtop'%>
                        <% end %>
                        <%= link_to "", edit_apartment_path(apartment), class:"fa fa-pencil-square-o property-type-icon" %>
                        <%= link_to apartment_path(apartment), method: :delete, data: { confirm: 'Are you sure?' }, class:"featured" do %>
                        <i class="fa fa-times-circle"></i>Delete
                        <%end %>
                    </div>
                    <div class="desc-box">
                        <h4><a href="#">Room: <%= apartment.room %></a></h4>
                        <ul class="slide-item-features item-features">
                            <li><span class="fa fa-arrows-alt"></span><%= apartment.area %> m<sup>2</sup></li>
                            <li><span class="fa fa-building-o"></span><%= apartment.floor.ordinalize %> floor</li>
                        </ul>
                        <div class="buttons-wrapper">
                            <a href="#" class="yellow-btn"><%= number_to_currency(apartment.price,precision:0,unit:"VND ") %></a>
                            <%= link_to apartment_path(apartment), class:"gray-btn" do %>
                            <span class="fa fa-file-text-o"></span>Detail
                            <% end %>
                        </div>
                        <div class="clearfix">
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Single-item -->
            <% end %>
        </div>
    </div>
</div>                                        
<!-- ▲block_listings -->

bms/app/views/apartments/new.html.erb
<div class="block-border">
	<div class="block-content">
		<h2>New apartment</h2>
		<%= render 'form' %>
	</div>
</div>

bms/app/views/apartments/show.html.erb
<style>
.container {
    padding-right: 0!important;
    padding-left: 0!important;
    width: 1170px;
}

#one_maincolumn #detailrightbloc {
    width: 61%;
    float: right;
}
</style>
<div id="one_maincolumn">
    <div class="container">
        <div id="detailarea" class="clearfix">
            <div id="detailphotobloc">
                <div class="photo">
                    <%= image_tag "07_img-6.png" ,:class => 'picture'%>
                </div>
            </div>
            <div id="detailrightbloc">
                <h1 class="product_name">Room: <%= @apartment.room %></h1>
                <div class="product_info_content">
                    <div class="product_info">
                        <span class="fa fa-arrows-alt"></span>
                        <%= @apartment.area %>  m<sup>2</sup>
                    </div>
                    <div class="product_info">
                        <span class="fa fa-building-o"></span>
                        <%= @apartment.floor.ordinalize %> floor
                    </div>
                    <dl class="price_format">
                        <span id="price01_default"><%= number_to_currency(@apartment.price,precision:0,unit:"VND ") %></span><span id="price01_dynamic"></span>
                    </dl>
                </div>             

                <div class="contact_content">
                    <div class="">
                        <h2 class="title_mail">
                            <span class="text semibold">Please contact us for more information</span>
                        </h2>
                    </div>
                    <form id="interestForm_" name="interestedForm" action="http://www.homegreekhome.com/en/requests/visitRequestSubmit/2252838" method="post" class="formContainer   columns nested ">
                        <div class="mainEnquireForm__leftColumn columns    nested ">
                            <div class="padding-left-large   borderBox">
                                <div class="margin-small"> 
                                    <input type="text" class="autoReset borderBox round_corners emptyText" id="fv_firstNameReq" name="fv_firstNameReq" value="" title="First name" placeholder="First name">
                                </div>
                                <div class="margin-small">
                                    <input type="text" class="autoReset borderBox round_corners emptyText" id="fv_lastNameReq" name="fv_lastNameReq" value="" title="Last name" placeholder="Last name">
                                </div>
                                <div class="margin-small">
                                    <input type="text" class="autoReset borderBox round_corners" id="fv_phoneNumberReq" name="fv_phoneNumberReq" value="" title="Mobile" placeholder="Mobile">
                                </div>
                                <div class="margin-small">
                                    <input type="text" class="autoReset borderBox round_corners" id="fv_contactEmail" name="fv_contactEmail" value="" title="Email" placeholder="Email">
                                </div>
                            </div>    
                        </div>
                        <div class="mainEnquireForm__rightColumn   columns    nested  ">
                            <div class=" padding-left-large  borderBox">
                                <div class="margin-small">
                                    <textarea id="fv_messageText" name="fv_messageText" class="borderBox round_corners margin-small-bottom"></textarea>
                                </div>
                                <div class="clear"></div>
                                <div id="requestSubmit_" >
                                    <a href="#" rel="nofollow"  class="orrange-btn">
                                        <i class="fa fa-envelope text medium"></i>&nbsp;  <span>Send email</span><span class="hidden refreshIcon margin-left"><i class="fa fa-refresh  fa-spin block"></i></span>
                                    </a>
                                </div>          
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>